# Generated by Django 5.1.4 on 2025-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketmodel',
            name='pay',
            field=models.CharField(choices=[('Mbank', 'Mbank'), ('Optima', 'Optima'), ('Visa', 'Visa')], max_length=100),
        ),
    ]
